- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
    state: present
